# Generated by Django 4.2.4 on 2023-09-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "PENDING"), ("Paid", "PAID")], max_length=7
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Payment", "PAYMENT"), ("Fine", "FINE")], max_length=7
                    ),
                ),
                ("borrowing_id", models.IntegerField()),
                ("session_url", models.URLField()),
                ("session_id", models.CharField(max_length=100)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
