# Generated by Django 4.2.4 on 2023-09-06 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_daily_fee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"]},
        ),
    ]
