# Generated by Django 4.2.4 on 2023-09-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0003_alter_borrowing_actual_return_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrowing',
            name='check_expected_return_date_gt_borrow_date',
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='expected_return_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.CheckConstraint(check=models.Q(('expected_return_date__gt', models.F('borrow_date'))), name='check_expected_return_date_gt_borrow_date', violation_error_message='Expected return date should be greater than borrow date'),
        ),
    ]
