# Generated by Django 4.2.4 on 2023-09-03 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "borrowings",
            "0004_remove_borrowing_check_expected_return_date_gt_borrow_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="check_actual_return_date_gte_expected_return_date",
        ),
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="check_expected_return_date_gt_borrow_date",
        ),
    ]
